"""
This type stub file was generated by pyright.
"""

from typing import Any, List, Optional, Sequence
from .common_types import _devices_t
from ..modules import Module

"""
This type stub file was generated by pyright.
"""
def parallel_apply(modules: Sequence[Module], inputs: Sequence[Any], kwargs_tup: Optional[Any] = ..., devices: Optional[_devices_t] = ...) -> List[Any]:
    ...

