"""
This type stub file was generated by pyright.
"""

import torch
import weakref

"""
This type stub file was generated by pyright.
"""
class EnabledProxy:
    """Stores whether the JIT is enabled or not.

    This is just a wrapper for a bool, so that we get reference semantics
    """
    def __init__(self) -> None:
        ...
    
    def parse_env(self, name, default, true_message, false_message):
        ...
    
    def __bool__(self):
        ...
    


_enabled = EnabledProxy()
def disable():
    ...

def enable():
    ...

_python_cu = torch._C.CompilationUnit()
_script_classes = {  }
_jit_caching_layer: weakref.WeakKeyDictionary = weakref.WeakKeyDictionary()
_jit_function_overload_caching: weakref.WeakKeyDictionary = weakref.WeakKeyDictionary()
