"""
This type stub file was generated by pyright.
"""

from typing import Optional

def get_enum(reduction: str) -> int:
    ...

def legacy_get_string(size_average: Optional[bool], reduce: Optional[bool], emit_warning: bool = ...) -> str:
    ...

def legacy_get_enum(size_average: Optional[bool], reduce: Optional[bool], emit_warning: bool = ...) -> int:
    ...

