"""
This type stub file was generated by pyright.
"""

import builtins
from .. import Tensor

"""
This type stub file was generated by pyright.
"""
class Parameter(Tensor):
    def __init__(self, data: Tensor = ..., requires_grad: builtins.bool = ...) -> None:
        ...
    


