"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
storage_classes = ['DoubleStorageBase', 'FloatStorageBase', 'LongStorageBase', 'IntStorageBase', 'ShortStorageBase', 'CharStorageBase', 'ByteStorageBase', 'BoolStorageBase', 'BFloat16StorageBase', 'ComplexDoubleStorageBase', 'ComplexFloatStorageBase']
def add_docstr_all(method, docstr):
    ...

