"""
This type stub file was generated by pyright.
"""

import os

"""
This type stub file was generated by pyright.
"""
if os.path.basename(os.path.dirname(__file__)) == 'shared':
    torch_parent = os.path.dirname(os.path.dirname(os.path.dirname(__file__)))
else:
    torch_parent = os.path.dirname(os.path.dirname(__file__))
def get_file_path(*path_components):
    ...

def get_file_path_2(*path_components):
    ...

def get_writable_path(path):
    ...

def prepare_multiprocessing_environment(path):
    ...

def resolve_library_path(path):
    ...

def get_source_lines_and_file(obj, error_msg=...):
    """
    Wrapper around inspect.getsourcelines and inspect.getsourcefile.

    Returns: (sourcelines, file_lino, filename)
    """
    ...

TEST_MASTER_ADDR = '127.0.0.1'
TEST_MASTER_PORT = 29500
USE_GLOBAL_DEPS = True
USE_RTLD_GLOBAL_WITH_LIBTORCH = False
