"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
_sparse_tensors_to_validate = []
def annotate(ret, **kwargs):
    ...

class KeyErrorMessage(str):
    r"""str subclass that returns itself in repr"""
    def __repr__(self):
        ...
    


class ExceptionWrapper(object):
    r"""Wraps an exception plus traceback to communicate across threads"""
    def __init__(self, exc_info=..., where=...) -> None:
        ...
    
    def reraise(self):
        r"""Reraises the wrapped exception in the current thread"""
        ...
    


