"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class _StorageBase(object):
    is_cuda = ...
    is_sparse = ...
    def __str__(self) -> str:
        ...
    
    def __repr__(self):
        ...
    
    def __iter__(self):
        ...
    
    def __copy__(self):
        ...
    
    def __deepcopy__(self, memo):
        ...
    
    def __reduce__(self):
        ...
    
    def __sizeof__(self):
        ...
    
    def clone(self):
        """Returns a copy of this storage"""
        ...
    
    def tolist(self):
        """Returns a list containing the elements of this storage"""
        ...
    
    def cpu(self):
        """Returns a CPU copy of this storage if it's not already on the CPU"""
        ...
    
    def double(self):
        """Casts this storage to double type"""
        ...
    
    def float(self):
        """Casts this storage to float type"""
        ...
    
    def half(self):
        """Casts this storage to half type"""
        ...
    
    def long(self):
        """Casts this storage to long type"""
        ...
    
    def int(self):
        """Casts this storage to int type"""
        ...
    
    def short(self):
        """Casts this storage to short type"""
        ...
    
    def char(self):
        """Casts this storage to char type"""
        ...
    
    def byte(self):
        """Casts this storage to byte type"""
        ...
    
    def bool(self):
        """Casts this storage to bool type"""
        ...
    
    def bfloat16(self):
        """Casts this storage to bfloat16 type"""
        ...
    
    def complex_double(self):
        """Casts this storage to complex double type"""
        ...
    
    def complex_float(self):
        """Casts this storage to complex float type"""
        ...
    
    def pin_memory(self):
        """Copies the storage to pinned memory, if it's not already pinned."""
        ...
    
    def share_memory_(self):
        """Moves the storage to shared memory.

        This is a no-op for storages already in shared memory and for CUDA
        storages, which do not need to be moved for sharing across processes.
        Storages in shared memory cannot be resized.

        Returns: self
        """
        ...
    


