"""
This type stub file was generated by pyright.
"""

from typing import List
from enum import Enum

"""
This type stub file was generated by pyright.
"""
class ProfilerState(Enum):
    Disable = ...
    CPU = ...
    CUDA = ...
    NVTX = ...


class ProfilerConfig:
    def __init__(self, state: ProfilerState, report_input_shapes: bool, profile_memory: bool, with_stack: bool) -> None:
        ...
    


class ProfilerEvent:
    def cpu_elapsed_us(self, other: ProfilerEvent) -> float:
        ...
    
    def cpu_memory_usage(self) -> int:
        ...
    
    def cuda_elapsed_us(self, other: ProfilerEvent) -> float:
        ...
    
    def cuda_memory_usage(self) -> int:
        ...
    
    def device(self) -> int:
        ...
    
    def handle(self) -> int:
        ...
    
    def has_cuda(self) -> bool:
        ...
    
    def is_remote(self) -> bool:
        ...
    
    def kind(self) -> int:
        ...
    
    def name(self) -> str:
        ...
    
    def node_id(self) -> int:
        ...
    
    def sequence_nr(self) -> int:
        ...
    
    def shapes(self) -> List[List[int]]:
        ...
    
    def thread_id(self) -> int:
        ...
    


