"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
def rangePushA(message: str) -> int:
    ...

def rangePop() -> int:
    ...

def markA(message: str) -> None:
    ...

