"""
This type stub file was generated by pyright.
"""

import torch

"""
This type stub file was generated by pyright.
"""
class BatchNorm2d(torch.nn.BatchNorm2d):
    r"""This is the quantized version of :class:`~torch.nn.BatchNorm2d`.
    """
    def __init__(self, num_features, eps=..., momentum=...) -> None:
        ...
    
    def forward(self, input):
        ...
    
    @classmethod
    def from_float(cls, mod):
        ...
    


class BatchNorm3d(torch.nn.BatchNorm3d):
    r"""This is the quantized version of :class:`~torch.nn.BatchNorm3d`.
    """
    def __init__(self, num_features, eps=..., momentum=...) -> None:
        ...
    
    def forward(self, input):
        ...
    
    @classmethod
    def from_float(cls, mod):
        ...
    


