"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
def hide_packed_params_repr(self, params):
    ...

_pair_from_first = _ntuple_from_first(2)
