"""
This type stub file was generated by pyright.
"""

import torch.nn.quantized as nnq

"""
This type stub file was generated by pyright.
"""
class BNReLU2d(nnq.BatchNorm2d):
    r"""
    A BNReLU2d module is a fused module of BatchNorm2d and ReLU

    We adopt the same interface as :class:`torch.nn.quantized.BatchNorm2d`.

    Attributes:
        Same as torch.nn.quantized.BatchNorm2d

    """
    _FLOAT_MODULE = ...
    def __init__(self, num_features, eps=..., momentum=...) -> None:
        ...
    
    def forward(self, input):
        ...
    
    @classmethod
    def from_float(cls, mod):
        ...
    


class BNReLU3d(nnq.BatchNorm3d):
    r"""
    A BNReLU3d module is a fused module of BatchNorm3d and ReLU

    We adopt the same interface as :class:`torch.nn.quantized.BatchNorm3d`.

    .. note::
    Attributes: Same as torch.nn.quantized.BatchNorm3d

    """
    _FLOAT_MODULE = ...
    def __init__(self, num_features, eps=..., momentum=...) -> None:
        ...
    
    def forward(self, input):
        ...
    
    @classmethod
    def from_float(cls, mod):
        ...
    


