"""
This type stub file was generated by pyright.
"""

import sys
import torch

"""
This type stub file was generated by pyright.
"""
def is_built():
    r"""Returns whether PyTorch is built with CUDA support.  Note that this
    doesn't necessarily mean CUDA is available; just that if this PyTorch
    binary were run a machine with working CUDA drivers and devices, we
    would be able to use it."""
    ...

class cuFFTPlanCacheAttrContextProp(object):
    def __init__(self, getter, setter) -> None:
        ...
    
    def __get__(self, obj, objtype):
        ...
    
    def __set__(self, obj, val):
        ...
    


class cuFFTPlanCache(object):
    r"""
    Represents a specific plan cache for a specific `device_index`. The
    attributes `size` and `max_size`, and method `clear`, can fetch and/ or
    change properties of the C++ cuFFT plan cache.
    """
    def __init__(self, device_index) -> None:
        ...
    
    size = ...
    max_size = ...
    def clear(self):
        ...
    


class cuFFTPlanCacheManager(object):
    r"""
    Represents all cuFFT plan caches. When indexed with a device object/index,
    this object returns the `cuFFTPlanCache` corresponding to that device.

    Finally, this object, when used directly as a `cuFFTPlanCache` object (e.g.,
    setting the `.max_size`) attribute, the current device's cuFFT plan cache is
    used.
    """
    __initialized = ...
    def __init__(self) -> None:
        ...
    
    def __getitem__(self, device):
        ...
    
    def __getattr__(self, name):
        ...
    
    def __setattr__(self, name, value):
        ...
    


class cuBLASModule:
    def __getattr__(self, name):
        ...
    
    def __setattr__(self, name, value):
        ...
    


cufft_plan_cache = cuFFTPlanCacheManager()
matmul = cuBLASModule()
