"""
This type stub file was generated by pyright.
"""

import ast
from typing import List, Optional, Tuple

class _ExtractModuleReferences(ast.NodeVisitor):
    """
    Extract the list of global variables a block of code will read and write
    """
    @classmethod
    def run(cls, src: str, package: str) -> List[Tuple[str, Optional[str]]]:
        ...
    
    def __init__(self, package) -> None:
        ...
    
    def visit_Import(self, node):
        ...
    
    def visit_ImportFrom(self, node):
        ...
    


find_files_source_depends_on = _ExtractModuleReferences.run
