"""
This type stub file was generated by pyright.
"""

from .optimizer import Optimizer, _params_t

"""
This type stub file was generated by pyright.
"""
class RMSprop(Optimizer):
    def __init__(self, params: _params_t, lr: float = ..., alpha: float = ..., eps: float = ..., weight_decay: float = ..., momentum: float = ..., centered: bool = ...) -> None:
        ...
    


