"""
This type stub file was generated by pyright.
"""

import os.path as _osp
from .throughput_benchmark import ThroughputBenchmark

"""
This type stub file was generated by pyright.
"""
def set_module(obj, mod):
    ...

cmake_prefix_path = _osp.join(_osp.dirname(_osp.dirname(__file__)), 'share', 'cmake')
