"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
def fuse_conv_bn_eval(conv, bn):
    ...

def fuse_conv_bn_weights(conv_w, conv_b, bn_rm, bn_rv, bn_eps, bn_w, bn_b):
    ...

