"""
This type stub file was generated by pyright.
"""

import importlib
import os
import sys
from .cv2 import *
from .data import *

ci_and_not_headless = False
if sys.platform.startswith("linux") and ci_and_not_headless:
    ...
if sys.platform.startswith("linux") and ci_and_not_headless:
    ...
