"""
This type stub file was generated by pyright.
"""

import sys
import torch
import types
from typing import List

"""
This type stub file was generated by pyright.
"""
class _QEngineProp(object):
    def __get__(self, obj, objtype) -> str:
        ...
    
    def __set__(self, obj, val: str) -> None:
        ...
    


class _SupportedQEnginesProp(object):
    def __get__(self, obj, objtype) -> List[str]:
        ...
    
    def __set__(self, obj, val) -> None:
        ...
    


class QuantizedEngine(types.ModuleType):
    def __init__(self, m, name) -> None:
        ...
    
    def __getattr__(self, attr):
        ...
    
    engine = ...
    supported_engines = ...


engine: str
supported_engines: List[str]
