"""
This type stub file was generated by pyright.
"""

from .autocast_mode import autocast, custom_bwd, custom_fwd
from .grad_scaler import GradScaler

"""
This type stub file was generated by pyright.
"""
