"""
This type stub file was generated by pyright.
"""

import enum

"""
This type stub file was generated by pyright.
"""
class QuantType(enum.IntEnum):
    DYNAMIC = ...
    STATIC = ...
    QAT = ...


