"""
This type stub file was generated by pyright.
"""

import collections
import threading
from enum import Enum

_thread_local_tensor_tables = threading.local()
class RPCExecMode(Enum):
    SYNC = ...
    ASYNC = ...
    ASYNC_JIT = ...
    REMOTE = ...


class _InternalRPCPickler:
    r"""
    This class provides serialize() and deserialize() interfaces to serialize
    data to be "binary string + tensor table" format
    So for RPC python UDF function and args, non tensor data will be serialized
    into regular binary string, tensor data will be put into thread local tensor
    tables, this serialization format is consistent with builtin operator and args
    using JIT pickler. This format will make tensor handling in C++ much easier,
    e.g. attach tensor to distributed autograd graph in C++
    """
    def __init__(self) -> None:
        ...
    
    def serialize(self, obj):
        r"""
        Serialize non tensor data into binary string, tensor data into
        tensor table
        """
        ...
    
    def deserialize(self, binary_data, tensor_table):
        r"""
        Deserilize binary string + tensor table to original obj
        """
        ...
    


_internal_rpc_pickler = _InternalRPCPickler()
def serialize(obj):
    ...

def deserialize(binary_data, tensor_table):
    ...

PythonUDF = collections.namedtuple("PythonUDF", ["func", "args", "kwargs"])
RemoteException = collections.namedtuple("RemoteException", ["msg", "exception_type"])
