"""
This type stub file was generated by pyright.
"""

def get_cudnn_mode(mode):
    ...

class Unserializable(object):
    def __init__(self, inner) -> None:
        ...
    
    def get(self):
        ...
    
    def __getstate__(self):
        ...
    
    def __setstate__(self, state):
        ...
    


def init_dropout_state(dropout, train, dropout_seed, dropout_state):
    ...

