"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class StorageWeakRef(object):
    r"""A weak reference to a Storage.

    The cdata member is a Python number containing the integer representation of
    the Storage pointer."""
    def __init__(self, storage) -> None:
        ...
    
    def expired(self):
        ...
    
    def __del__(self):
        ...
    


class SharedCache(dict):
    """dictionary from multiprocessing handles to StorageWeakRef"""
    def __init__(self) -> None:
        ...
    
    def __setitem__(self, key, storage_ref):
        ...
    
    def free_dead_references(self):
        ...
    


shared_cache = SharedCache()
def rebuild_event(device, handle):
    ...

def reduce_event(event):
    ...

def rebuild_tensor(cls, storage, metadata):
    ...

def rebuild_cuda_tensor(tensor_cls, tensor_size, tensor_stride, tensor_offset, storage_cls, storage_device, storage_handle, storage_size_bytes, storage_offset_bytes, requires_grad, ref_counter_handle, ref_counter_offset, event_handle, event_sync_required):
    ...

def reduce_tensor(tensor):
    ...

def fd_id(fd):
    ...

def storage_from_cache(cls, key):
    ...

def rebuild_storage_fd(cls, df, size):
    ...

def rebuild_storage_filename(cls, manager, handle, size):
    ...

def rebuild_storage_empty(cls):
    ...

def reduce_storage(storage):
    ...

def init_reductions():
    ...

