"""
This type stub file was generated by pyright.
"""

from torch.distributions.exp_family import ExponentialFamily

"""
This type stub file was generated by pyright.
"""
class Exponential(ExponentialFamily):
    r"""
    Creates a Exponential distribution parameterized by :attr:`rate`.

    Example::

        >>> m = Exponential(torch.tensor([1.0]))
        >>> m.sample()  # Exponential distributed with rate=1
        tensor([ 0.1046])

    Args:
        rate (float or Tensor): rate = 1 / scale of the distribution
    """
    arg_constraints = ...
    support = ...
    has_rsample = ...
    _mean_carrier_measure = ...
    @property
    def mean(self):
        ...
    
    @property
    def stddev(self):
        ...
    
    @property
    def variance(self):
        ...
    
    def __init__(self, rate, validate_args=...) -> None:
        ...
    
    def expand(self, batch_shape, _instance=...):
        ...
    
    def rsample(self, sample_shape=...):
        ...
    
    def log_prob(self, value):
        ...
    
    def cdf(self, value):
        ...
    
    def icdf(self, value):
        ...
    
    def entropy(self):
        ...
    


