"""
This type stub file was generated by pyright.
"""

from torch.distributions.exp_family import ExponentialFamily

"""
This type stub file was generated by pyright.
"""
class Gamma(ExponentialFamily):
    r"""
    Creates a Gamma distribution parameterized by shape :attr:`concentration` and :attr:`rate`.

    Example::

        >>> m = Gamma(torch.tensor([1.0]), torch.tensor([1.0]))
        >>> m.sample()  # Gamma distributed with concentration=1 and rate=1
        tensor([ 0.1046])

    Args:
        concentration (float or Tensor): shape parameter of the distribution
            (often referred to as alpha)
        rate (float or Tensor): rate = 1 / scale of the distribution
            (often referred to as beta)
    """
    arg_constraints = ...
    support = ...
    has_rsample = ...
    _mean_carrier_measure = ...
    @property
    def mean(self):
        ...
    
    @property
    def variance(self):
        ...
    
    def __init__(self, concentration, rate, validate_args=...) -> None:
        ...
    
    def expand(self, batch_shape, _instance=...):
        ...
    
    def rsample(self, sample_shape=...):
        ...
    
    def log_prob(self, value):
        ...
    
    def entropy(self):
        ...
    


