"""
This type stub file was generated by pyright.
"""

from torch.distributions.exp_family import ExponentialFamily

"""
This type stub file was generated by pyright.
"""
class Normal(ExponentialFamily):
    r"""
    Creates a normal (also called Gaussian) distribution parameterized by
    :attr:`loc` and :attr:`scale`.

    Example::

        >>> m = Normal(torch.tensor([0.0]), torch.tensor([1.0]))
        >>> m.sample()  # normally distributed with loc=0 and scale=1
        tensor([ 0.1046])

    Args:
        loc (float or Tensor): mean of the distribution (often referred to as mu)
        scale (float or Tensor): standard deviation of the distribution
            (often referred to as sigma)
    """
    arg_constraints = ...
    support = ...
    has_rsample = ...
    _mean_carrier_measure = ...
    @property
    def mean(self):
        ...
    
    @property
    def stddev(self):
        ...
    
    @property
    def variance(self):
        ...
    
    def __init__(self, loc, scale, validate_args=...) -> None:
        ...
    
    def expand(self, batch_shape, _instance=...):
        ...
    
    def sample(self, sample_shape=...):
        ...
    
    def rsample(self, sample_shape=...):
        ...
    
    def log_prob(self, value):
        ...
    
    def cdf(self, value):
        ...
    
    def icdf(self, value):
        ...
    
    def entropy(self):
        ...
    


